myapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Your question will start with "Should I...', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    submit = SubmitField('Add Question')

myapp/comments/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import Comment
from myapp.comments.forms import CommentForm

comments = Blueprint('comments', __name__)

@comments.route('/<int:post_id>/addComment', methods=['GET', 'POST'])
@login_required
def add_comment(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(text=form.text.data, user_id=current_user.id, post_id=post_id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment Created')
        print('Comment was created')
        
    return redirect(url_for('posts.post', post_id=post_id))


@comments.route('/<int:comment_id>/update',methods=['GET','POST'])
@login_required
def update(comment_id):
    comment = Comment.query.get_or_404(comment_id)

    if comment.author != current_user:
        abort(403)

    form = CommentForm()

    if form.validate_on_submit():
        comment.text = form.text.data
        db.session.commit()
        flash('Comment Updated')
        return redirect(url_for('posts.post', post_id=comment.post_id))

    elif request.method == 'GET':
        form.text.data = comment.text

    return render_template('update_comment.html',title='Updating',form=form)


@comments.route('/<int:comment_id>/deleteComment',methods=['GET','POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    post_id=comment.post_id
    if comment.author != current_user:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment Deleted')
    return redirect(url_for('posts.post', post_id=post_id))

myapp/core/views.py
from flask import render_template, request, Blueprint
from myapp.models import Post

core = Blueprint('core', __name__)

@core.route('/')
def info():
    return render_template('info.html')

@core.route('/allPosts')
def index():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', posts=posts)

myapp/posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import Post, Comment, Vote
from myapp.posts.forms import PostForm
from myapp.comments.forms import CommentForm

posts = Blueprint('posts', __name__)

@posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, description=form.description.data, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Post Created')
        print('Post was created')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)

# Make sure the blog_post_id is an integer!

@posts.route('/<int:post_id>')
@login_required
def post(post_id):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    comments =  Comment.query.filter_by(target=post).order_by(Comment.date.desc()).paginate(page=page, per_page=5)
    vote = Vote.query.filter_by(target=post, user_id = current_user.id).first()
    pro_votes = Vote.query.filter_by(target=post, vote_pro = 1).count()
    votes_against = Vote.query.filter_by(target=post, vote_against = 1).count()
    return render_template('post.html', title=post.title, date=post.date, post=post, form=form, comments = comments, pro_votes = pro_votes, votes_against = votes_against, vote = vote)


@posts.route('/<int:post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post Deleted')
    return redirect(url_for('core.index'))

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, Post
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data) :

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

@users.route('/<username>')
@login_required
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date.desc()).paginate(page=page, per_page=5) 
    return render_template('user_posts.html', posts=posts, user=user)

myapp/votes/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import Vote


votes = Blueprint('votes', __name__)

@votes.route('/<int:post_id>/addVotePro', methods=['GET', 'POST'])
@login_required
def add_vote_pro(post_id):
  vote =  Vote.query.filter_by(post_id=post_id, user_id=current_user.id).first()
  if vote:
    if vote.vote_pro == 1:
      vote.vote_pro = 0
    else:
      vote.vote_pro = 1
    vote.vote_against = 0
    db.session.commit()
    flash('Comment Created')
    print('Vote was updated to pro')
  else:  
    vote = Vote(user_id=current_user.id, post_id=post_id, vote_pro = 1, vote_against=0)
    db.session.add(vote)
    db.session.commit()
    flash('Comment Created')
    print('Vote was created')
  return redirect(url_for('posts.post', post_id=post_id))    


@votes.route('/<int:post_id>/addVoteAgainst', methods=['GET', 'POST'])
@login_required
def add_vote_against(post_id):
  vote =  Vote.query.filter_by(post_id=post_id, user_id=current_user.id).first()
  print(vote)
  if vote:
    if vote.vote_against == 1:
      vote.vote_against = 0
    else:
      vote.vote_against = 1
    vote.vote_pro = 0
    db.session.commit()
    flash('Comment Created')
    print('Vote was updated to against')
  else:  
    vote = Vote(user_id=current_user.id, post_id=post_id, vote_pro = 0, vote_against=1)
    db.session.add(vote)
    db.session.commit()
    flash('Comment Created')
    print('Vote was created')      
  return redirect(url_for('posts.post', post_id=post_id))

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}

<h1>Hey, {{current_user.username}}!</h1>

<div id="account-container" class="create-container">
    <form id="account" class="create-form" method="POST" action="" enctype="multipart/form-data">
       
            {{form.hidden_tag()}}
        
            {{form.username.label(class='form-group')}} 
            {{form.username(class='form-control text-in-form')}}
            <br>
            {{form.email.label(class='form-group')}} 
            {{form.email(class='form-control text-in-form')}}
            <br>
            {{form.submit(class='btn-update')}}
    
    </form>
</div>
<a id="account-btn" class="btn-prim" href="{{url_for('users.user_posts', username=current_user.username)}}">My Posts</a>

{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/style.css') }}">
    <link rel= "shortcut icon" type="image/jpg" href= "{{ url_for('static',filename='styles/images/favicon.png') }}">
    <title>Should I do that?</title>
</head>

<body>
    <nav id="main-nav">
        <a href="{{url_for('core.index')}}">All Posts</a>
        <a href="{{url_for('core.info')}}">About</a>

        {% if current_user.is_authenticated %}
            <a href="{{url_for('posts.create_post')}}">Create Post</a> 
            <a href="{{url_for('users.account')}}">Account</a>
            <a href="{{url_for('users.logout')}}">Log Out</a>
        {% else %}
            <a href="{{url_for('users.login')}}">Log In</a>
            <a href="{{url_for('users.register')}}">Register</a>
        {% endif %}
    </nav>
    
{% block content %}

{% endblock %}
    
</body>
</html>

myapp/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="create-container">
      <form class="create-form" method="POST">
          {{form.hidden_tag()}}
              {{form.title.label(class="form-control-label")}}
              {{form.title(class="form-control form-control-lg text-in-form", placeholder="Enter your question here...")}}
            <br>
            {{form.description.label(class="form-control-label")}}
            {{form.description(class="form-control form-control-lg text-in-form", placeholder="Describe your situation...")}}
            <br>
            {{form.submit(class="btn-prim")}}
        
      </form>
    </div>
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>All Posts</h1>
<main class="index-main">
    {% for each_post in posts.items %}
        <div class="post">
            <img id="post-img" src="/static/styles/images/decision2.png" alt="post-img">
            <div class="post-body">
                <div class="description-container">
                <h1>
                    "Should I {{each_post.title}}?"
                </h1>
                </div>
                <p>Posted by <a href="{{url_for('users.user_posts', username=each_post.author.username)}}">{{each_post.author.username}}</a> on {{each_post.date.strftime('%B %d, %Y')}}</p>
                <a class="btn-prim" href="{{url_for('posts.post', post_id=each_post.id)}}">Read Post</a>
            </div>
        </div>
    {% endfor %}
    
    </main>

    <nav aria-label="Page Navigation example">
        <ul class="pagination justify-content-center">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if posts.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item pag">
                    <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
    
{% endblock %}

myapp/templates/info.html
{% extends "base.html" %}
{% block content %}
    <main id="info" class="post-main">
        <h1>Welcome to "Should I do that?"</h1>
        <h2>Have a hard time making a decision? Need some advice? "Should I do that?" is here to help!<br> 
        Post your question and see what other people have to say about it. Good luck!</h2>
    </main>
   
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}

<form class="login-form" method="POST">
    {{form.hidden_tag()}}
    
    {{form.email.label}}<br>{{form.email(class="field")}}<br>
    {{form.password.label}}<br>{{form.password(class="field")}}<br>
    {{form.submit(class="btn-prim")}}
    <p class="page-text">Do not have an account? <a href="{{url_for('users.register')}}">Register</a></p>
</form>

{% endblock %}

myapp/templates/post.html
{% extends "base.html" %}
{% block content %}
<main class="post-main">
  <div id="post-container">
    <p>On {{ post.date.strftime('%B %d, %Y') }} {{ post.author.username }} asked:</p>
    <div class="description-container">
    <h1>Should I {{ post.title }}?</h1>
    <h2>{{post.description}}</h2>
    </div>
    <p class="votes">{{pro_votes}} people think {{ post.author.username }} should do that <br> {{votes_against}} people think {{ post.author.username }} shouldn't do that</p>
    {% if post.author == current_user %}
      <div>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
          <input class="btn-delete" type="submit" value="Delete Post">
        </form>
      </div>
      {% else %}
      {% if vote.vote_pro %}
        <p class="votes" >You voted pro</p>
        {% elif vote.vote_against %}
        <p class="votes">You voted against</p>
        {% else %}
        <p class="votes">You haven't voted yet</p>
        {% endif %}
     <div class="btn-container">
      <form action="{{ url_for('votes.add_vote_pro', post_id=post.id) }}" method="POST">
        <input class="btn btn-update" type="submit" value="Vote Pro">
      </form>
     
      <form action="{{ url_for('votes.add_vote_against', post_id=post.id) }}" method="POST">
        <input class="btn-delete" type="submit" value="Vote Against">
      </form>
     </div>
   {% endif %}
  </div>
   
  <h1>Comments</h1>
  
    <form class="comment-form"
    method="POST" action="{{ url_for('comments.add_comment', post_id=post.id) }}">
        {{form.hidden_tag()}}
          {{form.text.label(class="hidden")}}
          {{form.text(class="text-box", placeholder="Enter your comment here...")}}<br>
          {{form.submit(class="btn-prim")}}
    </form>
  
     <div class="container">
      {% for comment in comments.items %}
      <div class="card">
          <div class="card-body">
            <p>Commented by {{comment.author.username}} on {{comment.date.strftime('%B %d, %Y')}}</p>
            <h2>{{comment.text}}</h2>
          </div>
          {% if comment.author == current_user %}
            <div class="btn-container">
              <a class="btn-update" href="{{ url_for('comments.update', comment_id=comment.id) }}">Update</a>
              <br>
              <form action="{{ url_for('comments.delete_comment', comment_id=comment.id) }}" method="POST">
                <input class="btn-delete" type="submit" value="Delete">
              </form>
            </div>
          {% endif %}
      </div>
  {% endfor %}
    </div>
   
  
<nav aria-label="Page Navigation example">
  <ul class="pagination justify-content-center">

      {% for page_num in comments.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if comments.page == page_num %}
          <li class="page-item disabled">
              <a class="page-link" href="{{url_for('posts.post', post_id=post.id, page=page_num)}}">{{ page_num }}</a>
          </li>
          {% else %}
          <li class="page-item">
              <a class="page-link" href="{{url_for('posts.post', post_id=post.id, page=page_num)}}">{{ page_num }}</a>
          </li>
          {% endif %}
      {% endfor %}
  </ul>
</nav>
</main>
{% endblock content %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}
   
<form class="login-form" method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}<br>{{form.email(class="field")}}<br>
    {{form.username.label}}<br>{{form.username(class="field")}}<br>
    {{form.password.label}}<br>{{form.password(class="field")}}<br>
    {{form.pass_confirm.label}}<br>{{form.pass_confirm(class="field")}}<br>
    {{form.submit(class="btn-prim")}}
</form>
{% endblock %}

myapp/templates/update_comment.html
{% extends "base.html" %}
{% block content %}
    <div class="create-container">
      <form class="create-form" method="POST">
          {{form.hidden_tag()}}
          
          
            {{form.text.label(class="form-control-label")}}
            {{form.text(class="form-control form-control-lg text-in-form")}}
            <br>
            {{form.submit(class="btn-prim")}}
        
      </form>
    </div>
{% endblock %}

myapp/templates/user_posts.html
{% extends "base.html" %}
{% block content %}
    <h1>{{user.username}}'s posts</h1>
    <main class="index-main">
        {% for each_post in posts.items %}
            <div class="post">
                <img id="post-img" src="/static/styles/images/decision2.png" alt="post-img">
                <div class="post-body">
                    <div class="description-container">
                    <h1>
                        "Should I {{each_post.title}}?"
                    </h1>
                    <h2>{{each_post.description}}</h2>
                    </div>
                    <p>Posted on {{each_post.date.strftime('%B %d, %Y')}}</p>
                    <a class="btn-prim" href="{{url_for('posts.post', post_id=each_post.id)}}">Post Details</a>
                </div>
            </div>
        {% endfor %}
        
    </main>

    <nav aria-label="Page Navigation example">
        <ul class="pagination justify-content-center">

            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if posts.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>


{% endblock %}